var Population = require('./population');

var Simulate = function(num, pop) {
  // run the simulation (num) number of times (num is number of generations)
  for (let i = 0; i < num; i++) {
    // get array of all the numerical chromosome values
    let chrom_vals = pop.chrom_vals;

    // get array of individual fitness scores (calculated based on numerical chrom vals)
    let fitness = pop.fitness;
    
    // get array of individual probablities of mating (calculated based on fitness scores)
    let probs = pop.probs;

    // create the same number of children as the starting pop by mating
    var new_pop = [];
    // pop.same = 0;
    for (let i = 0; i < pop.size; i++) {
      new_pop.push(pop.mate());
    }

    // initialize a new population using the pop generated by mating
    var pop_hash = {};
    pop_hash["population"] = new_pop;
    pop_hash["env"] = pop.env;

    pop = new Population(pop_hash);
  }

  return pop;
}

module.exports = Simulate;
